#!/bin/sh
#
# @name Generic bicopter
#
# @type bicopter
# @class Copter
#
# @output MAIN1 motor 1 left motor
# @output MAIN2 motor 2 right motor
# @output MAIN3 servo 1 left servo
# @output MAIN4 servo 2 right servo
# @output MAIN5 feed-through of RC AUX1 channel
# @output MAIN6 feed-through of RC AUX2 channel
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
# @output AUX4 feed-through of RC FLAPS channel
#
# @maintainer
#

sh /etc/init.d/rc.mc_defaults

set MIXER bicopter
#set MIXER hummingbird

set PWM_OUT 1234
